kind: Service
apiVersion: v1
metadata:
  name: "publisher"
spec:
  selector:
    app: "publisher"
    version: 1.0.0
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: ClusterIP