apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672  # AMQP port
    - protocol: TCP
      port: 15672  # Management UI port