# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD Pipeline GO Distributed System

on:
  push:
    branches: [ "integration-testing" ]
  pull_request:
    branches: [ "integration-testing" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Install dependencies for publisher
      working-directory: ./publisher
      run: |
        go mod tidy
        go mod download

    - name: test publisher
      working-directory: ./publisher
      run: |
        go test -v ./...

    # - name: Build publisher
    #   working-directory: ./publisher
    #   run: |
    #     go build -v ./...

    - name: Install dependencies for server
      working-directory: ./server
      run: |
        go mod tidy
        go mod download

    - name: test server
      working-directory: ./server
      run: |
        go test -v ./...

    # - name: Build server
    #   working-directory: ./server
    #   run: |
    #     go build -v ./...
